
pipeline:
  build:
    image: plugins/docker
    repo: rnorge/music
    secrets: [ docker_username, docker_password ]
    tags: 
      - latest
      - ${DRONE_TAG}
    when:
      event:
        - tag