name: Test And Build BOT
on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    env:
      CheckFiles: "bot.py cogs/"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ${CheckFiles}

      - name: Check with Isort
        run: |
          pip install isort
          isort --check --sp setup.cfg ${CheckFiles}
      - name: Sort with Isort
        if: failure()
        run: |
          isort --sp setup.cfg ${CheckFiles}
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: actions/auto
          commit-message: Changes done by tests
          committer: Roxedus <bot@roxedus.dev>
          title: Linter changed files

  build-and-push:
    needs: flake8
    runs-on: ubuntu-latest
    env:
      repo: rnorge/music
      ref: ${{github.ref}}
      DOCKER_USERNAME: roxedus
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          branch="${ref##*/}"
          docker build -t $repo:$branch -t $repo:$branch-${{github.sha}} .

      - name: Master tag
        if: github.ref == 'refs/heads/master'
        run: |
          branch="${ref##*/}"
          bot_ver=$(grep -i bot_version cogs/utils/bot_version.py | cut -d" " -f3 | tr -d \")
          docker tag $repo:$branch $repo:$bot_ver

      - name: Bump version and push tag
        if: github.ref == 'refs/heads/master'
        uses: mathieudutour/github-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry
        if: github.event.pull_request == false
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pushes the Docker image
        if: github.event.pull_request == false
        run: docker push $repo
